@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.level.gameevent;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;