@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.model;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;