@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.player.inventory;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;