@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.commands.arguments.item;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;