@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.ticks;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;