@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.color.block;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;