@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.entity;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;