@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.entity.animal.axolotl;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;