@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.main;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;