@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.syncher;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;