@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.profiling;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;