@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.commands.arguments.blocks;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;