@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.item.crafting;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;