@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.random;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;