@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.gui.spectator;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;