@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.model.geom;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;