@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.food;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;