@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.core.cauldron;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;