@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.protocol.status;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;