@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.level;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;