@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.packs.repository;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;