@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.valueproviders;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;