@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.obfuscate;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;