@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.protocol;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;