@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.player;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;