@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.model.dragon;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;