@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.entity.vehicle;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;