@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.level.progress;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;