@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.dedicated;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;