@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.phys;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;