@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.multiplayer.resolver;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;