@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.profiling.jfr.callback;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;