@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.level.block;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;