@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.core.dispenser;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;