@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.entity.monster.hoglin;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;