@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.scores.criteria;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;