@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.effect;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;