@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.commands.synchronization;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;