@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.server;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;