@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.commands.synchronization.brigadier;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;