@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.protocol.handshake;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;