@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.damagesource;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;