@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.scores;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;