@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.commands;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;