@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.core.particles;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;