@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.protocol.login;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;