@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.bossevents;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;