@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.network;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;