@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.entity.schedule;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;