@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.worldupdate;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;