@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.protocol.game;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;