@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.particle;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;