@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.inventory.tooltip;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;