@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.packs;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;