@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.profiling;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;