@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.phys.shapes;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;