@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.commands;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;