@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.inventory;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;