@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.nbt.visitors;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;