@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.recipebook;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;