@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.level.redstone;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;