@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.tutorial;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;