@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.thread;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;