@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.profiling.jfr.serialize;

import com.workerai.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;